### ISSUE TITLE
Enable password hashing

### ISSUE THREAD

**Issue by sampsyo** [gvkarthik93/Zocalo#1]
Password hashing (with bcrypt) seems to be commented out: https://github.com/gvkarthik93/Zocalo/blob/028de816b5606129f8fb50a4abdcabca49dd0b14/service/user_service.py#L19

An easy way to add this would be to use the built-in password hashing functions in Python's `hashlib`:
https://docs.python.org/3.6/library/hashlib.html#hashlib.pbkdf2_hmac

Both PBKDF2 and scrypt are available there and are both suitable for storing passwords. (The `bcrypt` module could then be removed from `requirements.txt`.)

**Comment by carwithk** [comment]
Working on this now.

**Comment by sampsyo** [comment]
No need to rush! I don't intend issues to mean "you must work on this now!!!!!". The nice thing about an issue tracker is that it lets you keep track of the work that needs to be done without doing it immediately.

**Comment by carwithk** [comment]
Implemented and tested hashing.
