### ISSUE TITLE
No visual or URL change when filtering by tag

### ISSUE THREAD

**Issue by sampsyo** [gvkarthik93/Zocalo#6]
Clicking on the tags on the left-hand side of the main interface works, which is great! However:

- There's no visible indication that the user is looking at a filtered list. Perhaps the enabled tags can be highlighted to show what's currently active.
- The URL should probably also change when filtering by tag. This would make the "back" button work, for example, to go back to the full post list.
- It's not clear which posts have which tags. Perhaps a tag list should be shown in each post entry.

**Comment by alice86663766** [comment]
The active tag is now highlighted. Tags are also displayed in each post.

**Comment by sampsyo** [comment]
Nice! The visual indicators work great. The URL still doesn't change (and the back button doesn't work), but that is probably less important.
