### ISSUE TITLE
Use a top-level Python package

### ISSUE THREAD

**Issue by sampsyo** [gvkarthik93/Zocalo#9]
Manipulating `sys.path` to make `Zocalo` importable as a package, like this:
https://github.com/gvkarthik93/Zocalo/blob/e24ee6d6b6b0ab71fa205c8bc6444ec6a8afc0da/service/user_service.py#L4

…is a bit of a hack. The standard way to commit Python modules to git repositories avoids this. You make a top-level Python package, including its `__init__.py`, and put all your source files under there. (It's also customary for Python package names to be all lower case, so I recommend calling this directory `zocalo`, not `Zocalo`.) This way, you'll be able to say stuff like `import zocalo.service.user_service` consistently. (You can avoid relative, prefix-free imports like `import service.user_service` altogether!)

Then, you can create a "runner script" that lives *outside* of this package. That's the one you'll want to invoke to actually start the server. This can be really really simple—something like this:

```py
#!/usr/bin/env python
from zocalo.appserver import main
if __name__ == '__main__':
    main()
```

That lets you run `python3 that_new_script.py` from inside your git repository to kick things off.

**Comment by SihanC** [comment]
Changed it.
